we need to debug this exception
running AndroidNonspecific_Loop1
java.util.zip.ZipException: duplicate entry: AXMLPrinter2.jar
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:192)
	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
	at sun.tools.jar.Main.update(Main.java:572)
	at sun.tools.jar.Main.run(Main.java:220)
	at sun.tools.jar.Main.main(Main.java:1167)